### ISSUE TITLE
Assigning you things to do

### ISSUE THREAD

**Issue by andrewpak** [IanDLeon/LearningCpp#2]
I want you to look up how to create a markdown README file for your git repository, make the README, put some text in it explaining what this repo is for and push it. 

I also want you to write a program in C++ that prompts the user for an input (which will be an integer), takes that input, multiplies it by 100 and prints the result of that to the console. 

I also want you to give me access to the repo, so I can review your work.

Make another branch, switch to that branch, do all your work there and then open a pull request on your repository.

To create a new branch and switch to it 
`git branch <new_branch_name>`
`git checkout <your_branch_name>`

You have 24 hours, or else.

**Comment by andrewpak** [comment]
I also want you to give me access to the repo, so I can review your work. 

Time remaining 23 hours and 58 minutes. 

Thanks.

**Comment by andrewpak** [comment]
Make another branch, switch to that branch, do all your work there and then open a pull request on your repository.
To create a new branch and switch to it 
`git branch <new_branch_name>`
`git checkout <your_branch_name>`

**Comment by IanDLeon** [comment]
I got that done the only thing left is I have to push it into Github
